# https://theburningmonk.com/cloudformation-ref-and-getatt-cheatsheet/
# https://docs.aws.amazon.com/apigateway/latest/developerguide/import-api-aws-variables.html

AWSTemplateFormatVersion: 2010-09-09

Description: |
  Builds the infrastructure needed to run Concise, a URL-shortener like Bitly.

Resources:
  ConciseDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: concise-db

  ConciseLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ZipFile
      Handler: lambda_function.lambda_handler
      Runtime: python3.8

  ConciseLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principle:
              Service: lambda.amazonaws.com
              Action: sts.AssumeRole
        Path: /
        Policies:
          - PolicyName: concise-cloudwatch-logs
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: logs:CreateLogGroup
                  Resource:
                    Fn::Join:
                      - ":"
                      - - arn:aws:logs
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - "*"

                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: { "Fn::Join" : [":", ["arn:aws:logs", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "log-group", "/aws/lambda/*", "*" ]] }
                                 
  ConciseApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      BasePath: /
      Body:
        Son
      Target: !GetAtt ConciseLambdaFunction.Arn
